-- Add benchmark_standard column to career_vault table
ALTER TABLE career_vault 
ADD COLUMN IF NOT EXISTS benchmark_standard JSONB,
ADD COLUMN IF NOT EXISTS benchmark_generated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS benchmark_role_level TEXT;

-- Add index for faster benchmark queries
CREATE INDEX IF NOT EXISTS idx_career_vault_benchmark_generated 
ON career_vault(benchmark_generated_at) 
WHERE benchmark_standard IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN career_vault.benchmark_standard IS 'AI-generated personalized benchmark standard based on role, level, and industry. Generated by generate-benchmark-standard edge function.';
COMMENT ON COLUMN career_vault.benchmark_generated_at IS 'Timestamp when benchmark was last generated';
COMMENT ON COLUMN career_vault.benchmark_role_level IS 'Cached role level (Entry/Mid/Senior/Executive) for quick filtering';